# Report card

In [5]:
percentage = int(input("Enter your percentages"))

if(percentage <= 50):
    print("Grade D")
elif((percentage > 50)and(percentage <= 65)):
    print("Grade C")
elif((percentage > 65)and(percentage <= 80)):
    print("Greade B")
elif((percentage > 80)and(percentage <= 100)):
    print("Grade A")

Enter your percentages50
Grade D

# prime number 1 to 1000

In [24]:
for n in range(1,1001):
    count = 0
    for i in range(2,n):
        if(n % i == 0):
            count=count+1
            break
    if(count == 0):
            print(n)

1
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997

# tables

In [27]:
no = 10

for i in range(1,11):
    for j in range(1,11):
        print(i*j,end=' ')
    
    print("\n")

1 2 3 4 5 6 7 8 9 10

2 4 6 8 10 12 14 16 18 20

3 6 9 12 15 18 21 24 27 30

4 8 12 16 20 24 28 32 36 40

5 10 15 20 25 30 35 40 45 50

6 12 18 24 30 36 42 48 54 60

7 14 21 28 35 42 49 56 63 70

8 16 24 32 40 48 56 64 72 80

9 18 27 36 45 54 63 72 81 90

10 20 30 40 50 60 70 80 90 100